<?php require_once __DIR__.'/inc/head.phtml'; ?>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">CDN Dev-PHP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://blog.dev-php.site">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://portfolio.dev-php.site">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/dreboard">Github</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Dev-PHP
            <small>Content Delivery Network</small>
          </h1>

          <!-- Blog Post -->
          <div class="card mb-4">
              <form class="form-signin" method="post" action="">
                  <h2 class="form-signin-heading">Please sign in</h2>
                  <label for="inputEmail" class="sr-only">Email address</label>
                  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                  <label for="inputPassword" class="sr-only">Password</label>
                  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                  <div class="checkbox">
                      <label>
                          <input type="checkbox" value="remember-me"> Remember me
                      </label>
                  </div>
                  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
              </form>
            <div class="card-body">
              <h2 class="card-title">Scripts and Image Site</h2>
              <p class="card-text">The passcode form takes you into the upload center.
                <?php if (isset($name)) : ?>
              <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
              <?php else: ?>
              <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
              <?php endif; ?>

              </p>
              <a href="https://github.com/dreboard" class="btn btn-primary">See Code &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Updated on January 1, 2017 by
              <a href="#">Dev-PHP</a>
            </div>
          </div>


        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Login</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="passcode...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Images</a>
                    </li>
                    <li>
                      <a href="#">.js Files</a>
                    </li>
                    <li>
                      <a href="#">.css Files</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Fonts</a>
                    </li>
                    <li>
                      <a href="#">Files</a>
                    </li>
                    <li>
                      <a href="#">Videos</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Site Stuff</h5>
            <div class="card-body">
                <ul>
                    <li><a href="http://www.slimframework.com">Made with Bootstrap 4</a></li>
                    <li><a href="http://www.slimframework.com">SlimFramework</a></li>
                </ul>


            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

<?php require_once __DIR__.'/inc/foot.phtml'; ?>