<?php require_once __DIR__.'/../inc/head.phtml'; ?>
    <!-- Navigation -->
    <?php require_once __DIR__.'/../inc/nav_auth.phtml'; ?>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Dev-PHP
            <small>CDN Home</small>
          </h1>

          <!-- Blog Post -->
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title">Scripts and Image Site</h2>
              <p class="card-text">The passcode form takes you into the upload center.
                <?php if (isset($name)) : ?>
              <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
              <?php else: ?>
              <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
              <?php endif; ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col"></th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if (APPLICATION_ENV === 'development') {
                        try {
                            $dir    = __DIR__.'/../../public/files/';
                            $iterator = new FilesystemIterator($dir);
                            $filelist = array();
                            foreach($iterator as $entry) {
                                echo '<tr>
                                          <th scope="row">'.$entry->getFilename().'</th>
                                          <td>Mark</td>
                                          <td>Otto</td>
                                          <td>@mdo</td>
                                       </tr>
                                    ';
                            }
                        } catch (Exception $e) {
                            echo "Failure: " . $e->getMessage();
                        }
                    }
                    ?>
                    </tbody>
                </table>


                <p><a href="https://github.com/dreboard" class="btn btn-primary">See Code &rarr;</a></p>

            </div>
            <div class="card-footer text-muted">
              Updated on January 1, 2017 by
              <a href="#">Dev-PHP</a>
            </div>
          </div>


        </div>

        <!-- Sidebar Widgets Column -->
        <?php require_once __DIR__.'/../inc/side_auth.phtml'; ?>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

<?php require_once __DIR__.'/../inc/foot.phtml'; ?>