<!-- Footer -->
<footer class="py-5 bg-dark sticky-footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Dev-PHP 2018</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="http://cdn.dev-php.site/js/jquery.min.js"></script>
<script src="http://cdn.dev-php.site/js/bootstrap.bundle.min.js"></script>

</body>

</html>