<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <base href="http://cdn.dev-php.site/" />
    <?php if(APPLICATION_ENV === 'development'): ?>
        <meta http-equiv="Cache-control" content="public">
        <meta http-equiv="Cache-control" content="private">
        <meta http-equiv="Cache-control" content="no-cache">
        <meta http-equiv="Cache-control" content="no-store">
    <?php endif; ?>
    <script>
        var BASE_URL = 'http://cdn.dev-php.site/';
        var SITE_NAME = 'CDN';
        var APPLICATION_ENV = <?= APPLICATION_ENV; ?>;
    </script>
    <title>CDN Dev-PHP</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="http://cdn.dev-php.site/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.dev-php.site/css/blog-style.css" rel="stylesheet">
    <link href="http://cdn.dev-php.site/css/cdn.css" rel="stylesheet">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        if(APPLICATION_ENV === 'development'){
            ga('create', 'UA-104982459-2', 'auto'); // Development tracker
            ga('set', 'dimension1', SITE_NAME+'_DEV');
        } else {
            ga('create', 'UA-104982459-1', 'auto'); // Live tracker
            ga('set', 'dimension1', SITE_NAME);
        }

        ga('send', 'pageview');
    </script>
</head>

<body>