<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <base href="http://cdn.dev-php.site/" />
    <?php if(APPLICATION_ENV === 'development'): ?>
        <meta http-equiv="Cache-control" content="public">
        <meta http-equiv="Cache-control" content="private">
        <meta http-equiv="Cache-control" content="no-cache">
        <meta http-equiv="Cache-control" content="no-store">
    <?php endif; ?>
    <script>
        var BASE_URL = 'http://cdn.dev-php.site/';
        var SITE_NAME = 'CDN';
        var APPLICATION_ENV = <?= APPLICATION_ENV; ?>;
    </script>
    <title>CDN Dev-PHP</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="http://cdn.dev-php.site/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.dev-php.site/css/blog-style.css" rel="stylesheet">
    <style>
        .sticky-footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */
            height: 60px;
            background-color: #f5f5f5;
            font-family: 'Lato', sans-serif;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

    </style>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        if(APPLICATION_ENV === 'development'){
            ga('create', 'UA-104982459-2', 'auto'); // Development tracker
            ga('set', 'dimension1', SITE_NAME+'_DEV');
        } else {
            ga('create', 'UA-104982459-1', 'auto'); // Live tracker
            ga('set', 'dimension1', SITE_NAME);
        }

        ga('send', 'pageview');
    </script>
</head>

<body>